apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 1
  template:
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
        - name: goserver
          image: "edgaralmeida/hello-go:latest"

          resources:
            requests: 
              cpu: 100m
              memory: 20Mi
            limits:
              cpu: 500m
              memory: 25Mi

          # startupProbe:
          #   httpGet:
          #     path: /healthz
          #     port: 1337
          #   periodSeconds: 3
          #   failureThreshold: 1

          # readinessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: 1337
          #   initialDelaySeconds: 10
          #   periodSeconds: 3
          #   failureThreshold: 1

          # livenessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: 1337
          #   periodSeconds: 5
          #   failureThreshold: 1
          #   timeoutSeconds: 1
          #   successThreshold: 1

          envFrom:
            - configMapRef:
                name: configmap-env
            - secretRef:
                name: goserver-secret

          volumeMounts:
            - mountPath: "/go/fruits"
              name: config
              readOnly: true
            - mountPath: "/go/pvc"
              name: goserver-volume

      volumes:
        - name: goserver-volume
          persistentVolumeClaim:
            claimName: goserver-pvc

        - name: config
          configMap:
            name: configmap-fruits
            items:
              - key: fruits
                path: fruits.txt
