apiVersion: v1
kind: Service
metadata:
  name: goserver-service
spec:
  selector:
    app: goserver
  type: ClusterIP  
  # type: NodePort
  # type: LoadBalancer
  ports:
  - name: goserver-service
    port: 1337
    targetPort: 1337
    protocol: TCP
    # nodePort: 30001